package com.space.filling.curve;

import java.util.Hashtable;

public final class StateDiagram {
	int stateNo;
	String derivedKey;
	String nextDerivedKey;
	int nextState;
	
	public static StateDiagram[][] mapFrom2DimToOneDim()
	{
		StateDiagram[][] stateDiagram = new StateDiagram[4][4];
		StateDiagram curSD = null;
		Hashtable<String, Integer> str2IntKey = new Hashtable<String, Integer>();
		str2IntKey.put("00", 0);
		str2IntKey.put("01", 1);
		str2IntKey.put("10", 2);
		str2IntKey.put("11", 3);
		
		// state 0
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "00";
		curSD.nextDerivedKey = "00";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "01";
		curSD.nextDerivedKey = "01";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "10";
		curSD.nextDerivedKey = "11";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "11";
		curSD.nextDerivedKey = "10";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 1
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "00";
		curSD.nextDerivedKey = "00";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "01";
		curSD.nextDerivedKey = "11";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "10";
		curSD.nextDerivedKey = "01";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "11";
		curSD.nextDerivedKey = "10";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 2
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "00";
		curSD.nextDerivedKey = "10";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "01";
		curSD.nextDerivedKey = "01";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "10";
		curSD.nextDerivedKey = "11";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "11";
		curSD.nextDerivedKey = "00";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 3
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "00";
		curSD.nextDerivedKey = "10";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "01";
		curSD.nextDerivedKey = "11";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "10";
		curSD.nextDerivedKey = "01";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "11";
		curSD.nextDerivedKey = "00";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		return stateDiagram;
	}
	
	public static StateDiagram[][] mapFromOneDimTo2Dim()
	{
		StateDiagram[][] stateDiagram = new StateDiagram[4][4];
		StateDiagram curSD = null;
		Hashtable<String, Integer> str2IntKey = new Hashtable<String, Integer>();
		str2IntKey.put("00", 0);
		str2IntKey.put("01", 1);
		str2IntKey.put("10", 2);
		str2IntKey.put("11", 3);
		
		// state 0
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "00";
		curSD.nextDerivedKey = "00";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "01";
		curSD.nextDerivedKey = "01";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "10";
		curSD.nextDerivedKey = "11";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "11";
		curSD.nextDerivedKey = "10";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 1
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "00";
		curSD.nextDerivedKey = "00";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "01";
		curSD.nextDerivedKey = "10";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "10";
		curSD.nextDerivedKey = "11";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "11";
		curSD.nextDerivedKey = "01";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 2
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "00";
		curSD.nextDerivedKey = "11";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "01";
		curSD.nextDerivedKey = "01";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "10";
		curSD.nextDerivedKey = "00";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "11";
		curSD.nextDerivedKey = "10";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 3
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "00";
		curSD.nextDerivedKey = "11";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "01";
		curSD.nextDerivedKey = "10";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "10";
		curSD.nextDerivedKey = "00";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "11";
		curSD.nextDerivedKey = "01";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		return stateDiagram;
	}
	
	
	public static StateDiagram[][] mapFrom3DimToOneDim()
	{
		StateDiagram[][] stateDiagram = new StateDiagram[12][8];
		StateDiagram curSD = null;
		Hashtable<String, Integer> str2IntKey = new Hashtable<String, Integer>();
		str2IntKey.put("000", 0);
		str2IntKey.put("001", 1);
		str2IntKey.put("010", 2);
		str2IntKey.put("011", 3);
		str2IntKey.put("100", 4);
		str2IntKey.put("101", 5);
		str2IntKey.put("110", 6);
		str2IntKey.put("111", 7);
		
		// state 0
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 0;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 1
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 1;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 2
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 2;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 3
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 3;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 4
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 4;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 5
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 5;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 6
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 6;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 7
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 7;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 8
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 8;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 9
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 9;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 10
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 10;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 11
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 11;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		return stateDiagram;
	}
	
	public static StateDiagram[][] mapFromOneDimTo3Dim()
	{
		StateDiagram[][] stateDiagram = new StateDiagram[12][8];
		StateDiagram curSD = null;
		Hashtable<String, Integer> str2IntKey = new Hashtable<String, Integer>();
		str2IntKey.put("000", 0);
		str2IntKey.put("001", 1);
		str2IntKey.put("010", 2);
		str2IntKey.put("011", 3);
		str2IntKey.put("100", 4);
		str2IntKey.put("101", 5);
		str2IntKey.put("110", 6);
		str2IntKey.put("111", 7);
		
		// state 0
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 0;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 0;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 1
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 1;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 1;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 2
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 2;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 2;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 3
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 3;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 3;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 4
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 4;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 4;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 5
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 5;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 5;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 0;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 6
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 6;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 6;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 7
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 7;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 7;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 8
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 8;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 1;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 8;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 9;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 9
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 9;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 9;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 10
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 8;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 5;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 10;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 7;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 10;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 11;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		
		// state 11
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "000";
		curSD.nextDerivedKey = "011";
		curSD.nextState = 6;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "001";
		curSD.nextDerivedKey = "001";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "010";
		curSD.nextDerivedKey = "101";
		curSD.nextState = 3;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "011";
		curSD.nextDerivedKey = "111";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD.stateNo = 11;
		curSD.derivedKey = "100";
		curSD.nextDerivedKey = "110";
		curSD.nextState = 4;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "101";
		curSD.nextDerivedKey = "100";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "110";
		curSD.nextDerivedKey = "000";
		curSD.nextState = 10;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;		
		curSD = new StateDiagram();
		curSD.stateNo = 11;
		curSD.derivedKey = "111";
		curSD.nextDerivedKey = "010";
		curSD.nextState = 2;
		stateDiagram[curSD.stateNo][str2IntKey.get(curSD.derivedKey)] = curSD;
		
		return stateDiagram;
	}
	
	public static void main(String args[])
	{
		StateDiagram.mapFromOneDimTo2Dim();
	}
}

/**
class MappingValues {
	String keyValue;
	int nextState;
}*/